/** Subscription states as Stripe reports them; Paddle uses a subset. */
export type SubscriptionStatus =
  | 'incomplete'
  | 'incomplete_expired'
  | 'trialing'
  | 'active'
  | 'past_due'
  | 'paused'
  | 'unpaid'
  | 'canceled';

export const SUBSCRIPTION_STATUSES: readonly SubscriptionStatus[] = [
  'incomplete',
  'incomplete_expired',
  'trialing',
  'active',
  'past_due',
  'paused',
  'unpaid',
  'canceled'
];

/** Where a license comes from: a payment provider such as `stripe`, or `manual` for licenses granted by support. */
export type LicenseSource = string;

export const MANUAL_SOURCE = 'manual';

export type ManualReason = 'support' | 'creator' | 'testing' | 'promotion';

export const MANUAL_REASONS: readonly ManualReason[] = ['support', 'creator', 'testing', 'promotion'];

/** A support block ends Pro independently of billing, e.g. after abuse of the activation code. */
export type SupportStatus = 'none' | 'blocked';

/** Everything the license service stores about a license. No names, email addresses or payment data. */
export type LicenseRecord = {
  id: string;
  source: LicenseSource;
  /** Customer, subscription and status at the payment provider; `null` for manual licenses. */
  providerCustomerId: string | null;
  providerSubscriptionId: string | null;
  providerStatus: SubscriptionStatus | null;
  /** End of the paid period; for a past-due subscription, the start of the unpaid period. */
  currentPeriodEndsAt: string | null;
  /** A cancellation the customer scheduled for the end of the paid period. */
  scheduledCancelAt: string | null;
  canceledAt: string | null;
  /** Set after a full refund or a chargeback; cleared if the chargeback is reversed. */
  revokedAt: string | null;
  /** Manual licenses only: Pro ends here, or never if `null`. */
  manualValidUntil: string | null;
  manualReason: ManualReason | null;
  supportStatus: SupportStatus;
  /** Internal note of the support team. Must not contain names, addresses or payment data. */
  supportNote: string | null;
  /** Time of the newest provider event applied, so events that arrive late cannot overwrite newer data. */
  providerUpdatedAt: string | null;
  codeHash: string | null;
  codeIssuedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

/** A pseudonymous installation id generated by the app, never linked to a device name or user. */
export type InstallationRecord = {
  licenseId: string;
  installationId: string;
  secretHash: string;
  activatedAt: string;
  lastSeenAt: string;
  deactivatedAt: string | null;
};

export type SubscriptionUpdate = {
  provider: string;
  customerId: string;
  subscriptionId: string;
  status: SubscriptionStatus;
  currentPeriodEndsAt: string | null;
  scheduledCancelAt: string | null;
  canceledAt: string | null;
  occurredAt: string;
};

export type ActivationRequest = {
  licenseId: string;
  installationId: string;
  secretHash: string;
  now: string;
  maxActive: number;
  /** Deactivates this other installation of the same license first, e.g. an old computer. */
  replaceInstallationId?: string;
};

export interface LicenseStore {
  /** Creates the license on the first event of a subscription and ignores events older than the stored state. */
  applySubscription(
    update: SubscriptionUpdate,
    newId: () => string,
    now: string
  ): Promise<{ license: LicenseRecord; created: boolean; applied: boolean }>;
  findById(id: string): Promise<LicenseRecord | null>;
  findBySubscription(provider: string, subscriptionId: string): Promise<LicenseRecord | null>;
  findByCodeHash(codeHash: string): Promise<LicenseRecord | null>;
  findByCustomer(provider: string, customerId: string): Promise<LicenseRecord[]>;
  setActivationCode(licenseId: string, codeHash: string, now: string): Promise<void>;
  setRevoked(licenseId: string, revokedAt: string | null, now: string): Promise<void>;
  activeInstallations(licenseId: string): Promise<InstallationRecord[]>;
  findInstallation(licenseId: string, installationId: string): Promise<InstallationRecord | null>;
  /** Atomic, so parallel activations cannot exceed the limit. Re-activating an active installation replaces its secret. */
  activateInstallation(request: ActivationRequest): Promise<'activated' | 'limit-reached'>;
  touchInstallation(licenseId: string, installationId: string, now: string): Promise<void>;
  deactivateInstallation(licenseId: string, installationId: string, now: string): Promise<boolean>;
  /** `duplicate` only for events that were processed completely before. */
  beginWebhookEvent(eventId: string, eventType: string, occurredAt: string, now: string): Promise<'new' | 'duplicate'>;
  completeWebhookEvent(eventId: string, now: string): Promise<void>;
  /** Lets the provider's retry process a failed event again. */
  abandonWebhookEvent(eventId: string): Promise<void>;
  ping(): Promise<void>;
  close(): Promise<void>;
}

/** Keeps everything in memory, for tests and local development without PostgreSQL. */
export class MemoryLicenseStore implements LicenseStore {
  protected readonly licenses = new Map<string, LicenseRecord>();
  protected readonly installations: InstallationRecord[] = [];
  private readonly events = new Map<string, { processedAt: string | null }>();

  async applySubscription(update: SubscriptionUpdate, newId: () => string, now: string) {
    // The stored record itself, not a copy, so the update below is kept.
    const existing = [...this.licenses.values()].find(
      (license) => license.source === update.provider && license.providerSubscriptionId === update.subscriptionId
    );
    const fields = {
      providerCustomerId: update.customerId,
      providerStatus: update.status,
      currentPeriodEndsAt: update.currentPeriodEndsAt,
      scheduledCancelAt: update.scheduledCancelAt,
      canceledAt: update.canceledAt,
      providerUpdatedAt: update.occurredAt,
      updatedAt: now
    };
    if (!existing) {
      const license: LicenseRecord = {
        id: newId(),
        source: update.provider,
        providerSubscriptionId: update.subscriptionId,
        revokedAt: null,
        manualValidUntil: null,
        manualReason: null,
        supportStatus: 'none',
        supportNote: null,
        codeHash: null,
        codeIssuedAt: null,
        createdAt: now,
        ...fields
      };
      this.licenses.set(license.id, license);
      return { license: { ...license }, created: true, applied: true };
    }
    if (existing.providerUpdatedAt && Date.parse(update.occurredAt) < Date.parse(existing.providerUpdatedAt)) {
      return { license: { ...existing }, created: false, applied: false };
    }
    Object.assign(existing, fields);
    return { license: { ...existing }, created: false, applied: true };
  }

  async findById(id: string) {
    const license = this.licenses.get(id);
    return license ? { ...license } : null;
  }

  async findBySubscription(provider: string, subscriptionId: string) {
    const license = [...this.licenses.values()].find(
      (candidate) => candidate.source === provider && candidate.providerSubscriptionId === subscriptionId
    );
    return license ? { ...license } : null;
  }

  async findByCodeHash(codeHash: string) {
    const license = [...this.licenses.values()].find((candidate) => candidate.codeHash === codeHash);
    return license ? { ...license } : null;
  }

  async findByCustomer(provider: string, customerId: string) {
    return [...this.licenses.values()]
      .filter((license) => license.source === provider && license.providerCustomerId === customerId)
      .map((license) => ({ ...license }));
  }

  async setActivationCode(licenseId: string, codeHash: string, now: string) {
    this.update(licenseId, { codeHash, codeIssuedAt: now, updatedAt: now });
  }

  async setRevoked(licenseId: string, revokedAt: string | null, now: string) {
    this.update(licenseId, { revokedAt, updatedAt: now });
  }

  async activeInstallations(licenseId: string) {
    return this.installations
      .filter((installation) => installation.licenseId === licenseId && installation.deactivatedAt === null)
      .map((installation) => ({ ...installation }));
  }

  async findInstallation(licenseId: string, installationId: string) {
    const installation = this.find(licenseId, installationId);
    return installation ? { ...installation } : null;
  }

  async activateInstallation(request: ActivationRequest) {
    if (request.replaceInstallationId && request.replaceInstallationId !== request.installationId) {
      const replaced = this.find(request.licenseId, request.replaceInstallationId);
      if (replaced && replaced.deactivatedAt === null) replaced.deactivatedAt = request.now;
    }
    const existing = this.find(request.licenseId, request.installationId);
    const alreadyActive = existing?.deactivatedAt === null;
    const others = this.installations.filter(
      (installation) =>
        installation.licenseId === request.licenseId &&
        installation.deactivatedAt === null &&
        installation.installationId !== request.installationId
    );
    if (!alreadyActive && others.length >= request.maxActive) {
      return 'limit-reached' as const;
    }
    if (existing) {
      Object.assign(existing, { secretHash: request.secretHash, lastSeenAt: request.now, deactivatedAt: null });
      if (!alreadyActive) existing.activatedAt = request.now;
    } else {
      this.installations.push({
        licenseId: request.licenseId,
        installationId: request.installationId,
        secretHash: request.secretHash,
        activatedAt: request.now,
        lastSeenAt: request.now,
        deactivatedAt: null
      });
    }
    return 'activated' as const;
  }

  async touchInstallation(licenseId: string, installationId: string, now: string) {
    const installation = this.find(licenseId, installationId);
    if (installation) installation.lastSeenAt = now;
  }

  async deactivateInstallation(licenseId: string, installationId: string, now: string) {
    const installation = this.find(licenseId, installationId);
    if (!installation || installation.deactivatedAt !== null) return false;
    installation.deactivatedAt = now;
    return true;
  }

  async beginWebhookEvent(eventId: string, _eventType: string, _occurredAt: string, _now: string) {
    const event = this.events.get(eventId);
    if (event?.processedAt) return 'duplicate' as const;
    this.events.set(eventId, { processedAt: null });
    return 'new' as const;
  }

  async completeWebhookEvent(eventId: string, now: string) {
    this.events.set(eventId, { processedAt: now });
  }

  async abandonWebhookEvent(eventId: string) {
    this.events.delete(eventId);
  }

  async ping() {}

  async close() {}

  protected find(licenseId: string, installationId: string): InstallationRecord | undefined {
    return this.installations.find(
      (installation) => installation.licenseId === licenseId && installation.installationId === installationId
    );
  }

  protected update(licenseId: string, changes: Partial<LicenseRecord>): void {
    const license = this.licenses.get(licenseId);
    if (license) Object.assign(license, changes);
  }
}
